[build]
    command = "tsc --noEmit || true && vite build"
    publish = "dist"
    functions = "netlify/functions"


[[redirects]]
    from = "/ads.txt"
    to = "/ads.txt.html"
    status = 200
    force = true
