export const exampleQueries = [
  'Find a React component library with advanced accessibility features, extensive documentation, and support for server-side rendering',
  'Recommend a no-code platform for building mobile apps that integrates with popular APIs and has a visual drag-and-drop interface',
  'Suggest a Python data visualization library that handles large datasets efficiently and creates interactive, publication-quality plots',
  'I need a lightweight CSS framework optimized for rapid prototyping of responsive web designs with a small file size',
  'Find an open-source e-commerce platform with good SEO features and support for multiple payment gateways',
  'Recommend a JavaScript testing framework with excellent async support, easy setup, and integration with popular CI/CD tools',
  "I'm looking for a machine learning library in Python that's beginner-friendly but scalable for complex projects",
  'Suggest a project management tool with Gantt charts, resource allocation, and integration with version control systems',
  'Find a low-code platform for building internal tools that connects to various databases and has a rich set of pre-built components',
  'Recommend an icon library with a wide range of styles, easy customization options, and good documentation for developers',
  'I need a robust ORM for Node.js that supports multiple databases, has good performance, and an active community',
  "Find a design system that's customizable, has good documentation, and integrates well with popular front-end frameworks",
  'Suggest a headless CMS with a user-friendly interface, robust API, and support for multiple content types',
  "I'm looking for a data ETL tool that can handle various data sources, has a visual interface, and supports scheduling",
  "Recommend a static site generator that's fast, has good plugin support, and integrates well with headless CMSs",
  "Find a UI kit for Figma that's comprehensive, regularly updated, and includes components for web and mobile design",
  'Suggest a backend-as-a-service platform with good documentation, scalability options, and support for real-time data',
  'I need a video editing library for JavaScript that can handle basic operations like trimming and adding text overlays',
  'Recommend a natural language processing library in Python with pre-trained models and support for multiple languages',
  'Find a data visualization tool that creates interactive dashboards and can easily embed in web applications',
  'Suggest a cross-platform mobile development framework with native-like performance and a rich ecosystem of plugins',
  "I'm looking for a serverless platform with good local development tools, easy deployment, and support for multiple languages",
  'Recommend a UX research tool that helps with user testing, provides analytics, and integrates with design tools',
  'Find a GraphQL client library with good caching mechanisms, optimistic UI updates, and TypeScript support',
  'Suggest a web scraping library in Python that respects robots.txt, handles JavaScript-rendered content, and is easy to use',
  "I need a state management library for React that's lightweight, has good TypeScript support, and works well with hooks",
  'Recommend a tool for creating and managing API documentation that supports OpenAPI and has a user-friendly interface',
  'Find a database solution that supports both SQL and NoSQL models, has good scalability, and offers a free tier for startups',
  'Suggest a CSS-in-JS library that has good performance, supports server-side rendering, and has a small bundle size',
  "I'm looking for an A/B testing tool that integrates well with React applications and provides detailed analytics",
  "Recommend a continuous integration tool that's easy to set up, has good GitHub integration, and supports parallel builds",
  "Find a UI animation library for React that's performant, has a declarative API, and supports gestures",
  'Suggest a tool for monitoring and analyzing web application performance that provides actionable insights',
  'I need a form builder library for React that handles complex validations, supports file uploads, and is accessible',
  'Recommend a tool for creating interactive product tours and onboarding experiences in web applications',
  'Find a charting library that supports a wide range of chart types, is customizable, and performs well with large datasets',
  'Suggest a CRM system tailored for startups that integrates with popular marketing tools and has a user-friendly interface',
  "I'm looking for a website builder specifically designed for portfolios with customizable templates and good SEO features",
  'Recommend a tool for creating and managing design tokens that integrates with popular design tools and build processes',
  "Find a JavaScript date manipulation library that's lightweight, supports time zones, and has good localization options",
  "Suggest a tool for creating interactive infographics that doesn't require coding skills and offers various export options",
  'I need a library for adding PDF generation capabilities to a Node.js application with support for complex layouts',
  'Recommend a platform for creating and hosting technical documentation with good search functionality and version control',
  'Find a tool for generating realistic mock data for testing and development that supports various data types and formats',
  'Suggest a library for adding voice commands to a web application that works across different browsers and devices',
  "I'm looking for a platform to create and manage email templates with a drag-and-drop interface and dynamic content support",
  'Recommend a tool for monitoring and analyzing user behavior in web applications with heatmaps and session recordings',
  'Find a library for adding collaborative editing features to a web-based document editor with real-time sync',
  'Suggest a platform for creating and managing online courses with features like quizzes, certificates, and payment integration',
  "I need a tool for creating interactive 3D visualizations for the web that's performant and has a gentle learning curve",
  "Find a blockchain development framework that's beginner-friendly, has good documentation, and supports multiple cryptocurrencies",
  'Recommend a tool for creating interactive product configurators with 3D visualization capabilities and e-commerce integration',
  'Suggest a no-code platform for building internal tools that connects to various data sources and has a rich set of pre-built components',
  'I need a JavaScript library for creating interactive maps with custom overlays and support for real-time data updates',
  'Find a tool for automating social media posting across multiple platforms with analytics and content suggestion features',
  'Recommend an open-source alternative to Photoshop that runs in the browser and supports layer-based editing',
  'Suggest a platform for creating and managing API gateways with features like rate limiting, authentication, and analytics',
  "I'm looking for a library to add text-to-speech capabilities to a web application with support for multiple languages",
  'Find a tool for creating interactive flowcharts and diagrams that can be easily embedded in web applications',
  'Recommend a platform for building and deploying machine learning models without extensive coding, suitable for business analysts',
  'Suggest a library for adding augmented reality features to a mobile app with support for both iOS and Android',
  'I need a tool for creating and managing design systems that integrates with popular design tools and provides developer handoff features',
  'Find a platform for building conversational AI chatbots with natural language processing capabilities and multi-channel support',
  'Recommend a tool for creating interactive data stories and explanatory journalism pieces with built-in data visualization features',
  'Suggest a framework for building progressive web apps that work offline and provide a native app-like experience',
  "I'm looking for a platform to create and host technical documentation with features like versioning, search, and API reference generation",
  'Find a tool for monitoring and analyzing API performance and usage with alerts and detailed error reporting',
  'Recommend a library for adding real-time collaboration features to a web-based project management tool',
  'Suggest a platform for creating and managing online communities with features like discussion forums, member profiles, and content moderation',
  'I need a tool for generating realistic 3D avatars that can be customized and animated for use in web and mobile applications',
  'Find a low-code platform for building internal dashboards that connects to various data sources and offers drag-and-drop report building',
  'Recommend a library for adding video conferencing capabilities to a web application with features like screen sharing and recording',
  'Suggest a tool for creating interactive onboarding experiences for SaaS products with analytics and A/B testing capabilities',
  "I'm looking for a platform to build and deploy serverless functions across multiple cloud providers with a unified interface",
  'Find a tool for creating and managing design tokens that works across design tools and integrates with development workflows',
  'Recommend a library for adding image recognition and object detection capabilities to a mobile app with on-device processing',
  'Suggest a platform for creating and managing online marketplaces with features like seller management and commission handling',
  'I need a tool for automating end-to-end testing of web applications with support for different browsers and devices',
  'Find a library for adding voice recognition and natural language understanding to a virtual assistant application',
  'Recommend a platform for creating and managing digital asset management systems with AI-powered tagging and search capabilities',
  'Suggest a tool for creating interactive product demos and walkthroughs without coding, suitable for sales and marketing teams',
  "I'm looking for a library to add data visualization capabilities to a React Native app with support for various chart types",
  'Find a platform for building and deploying IoT applications with features like device management and data analytics',
  'Recommend a tool for creating and managing design systems that integrates with popular design tools and provides code snippets',
  'Suggest a library for adding facial recognition and emotion detection capabilities to a web application using the device camera',
  'I need a platform for creating and managing online courses with features like gamification, certificates, and payment integration',
  'Find a tool for monitoring and optimizing website performance with actionable recommendations and integration with popular CMSs',
  'Recommend a library for adding OCR (Optical Character Recognition) capabilities to a document scanning mobile app',
  'Suggest a platform for creating and managing affiliate marketing programs with tracking, reporting, and payment features',
  "I'm looking for a tool to automate the process of generating legal documents with customizable templates and e-signature support",
  'Find a library for adding 2D game development capabilities to a web application with physics simulation and sprite animation',
  'Recommend a platform for creating and managing employee training programs with features like skill assessments and learning paths',
  'Suggest a tool for creating interactive data visualizations that can be easily embedded in blogs and news articles',
  'I need a library for adding geospatial analysis capabilities to a web application with support for various map projections',
  'Find a platform for building and deploying edge computing applications with features like service mesh and distributed data storage',
  'Recommend a tool for creating and managing multilingual content for websites with translation workflow and version control features',
  'Suggest a library for adding speech-to-text capabilities to a podcast transcription application with support for multiple languages',
  "I'm looking for a platform to create and manage virtual events with features like networking rooms, live streaming, and analytics",
  'Find a tool for automating the process of generating API client libraries for multiple programming languages',
  'Recommend a library for adding advanced image editing capabilities to a web-based graphic design tool',
  "I'm developing a large-scale e-commerce platform and need a robust, scalable microservices architecture solution that supports event-driven communication, has built-in monitoring and tracing capabilities, integrates well with container orchestration tools like Kubernetes, and provides easy-to-use libraries for multiple programming languages including Java, Python, and Node.js.",

  'Looking for a comprehensive data analytics platform that can handle big data processing, supports both batch and stream processing, has built-in machine learning capabilities, provides interactive visualization tools, integrates with popular cloud storage solutions, and offers both SQL-like querying and programming interfaces for data scientists and analysts. It should also have strong security features and compliance certifications for GDPR and HIPAA.',

  'Need a sophisticated no-code/low-code platform for building enterprise-grade applications that supports visual process modeling, has a rich set of pre-built connectors for popular enterprise systems (like SAP, Salesforce, and Oracle), allows for custom code insertion when needed, provides robust user management and role-based access control, and can generate both web and mobile applications with offline capabilities. The platform should also support version control and have a clear audit trail for all changes.',

  'Searching for an advanced AI-powered content management system that uses natural language processing for automatic content categorization and tagging, supports multilingual content with built-in translation capabilities, has sophisticated personalization features based on user behavior and preferences, integrates seamlessly with popular marketing automation tools, provides headless CMS capabilities with a robust API, and includes built-in SEO optimization tools and analytics.',

  'I need a comprehensive DevOps platform that integrates continuous integration, continuous deployment, infrastructure as code, automated testing, and security scanning into a single, cohesive workflow. It should support multiple cloud providers, have built-in support for containerization and orchestration, provide detailed analytics and reporting on the entire software development lifecycle, and offer customizable compliance and governance features. Additionally, it should have a user-friendly interface for managing complex pipelines and support ChatOps integration for team collaboration.',

  'Looking for an all-in-one digital experience platform for creating and managing multi-channel customer experiences. It should include features for content management, e-commerce, customer data management, personalization, A/B testing, and analytics. The platform needs to support headless architecture for delivering content to various frontends (web, mobile, IoT devices), have robust API management capabilities, integrate with popular marketing tools, and provide AI-powered insights for optimizing user experiences across all touchpoints. It should also include features for managing user-generated content and have built-in moderation tools.',

  'Seeking a comprehensive business intelligence and data visualization tool that can connect to a wide variety of data sources (including big data platforms, cloud data warehouses, and real-time streaming data), supports complex data modeling and ETL processes, offers a wide range of customizable visualizations, has built-in statistical analysis and forecasting capabilities, supports collaborative dashboard creation and sharing, and provides natural language querying for non-technical users. The tool should also have strong data governance features, support for embedded analytics in other applications, and the ability to handle geospatial data visualization.',

  'Need an advanced IoT platform for developing and managing smart city applications. The platform should support ingestion and processing of data from various types of sensors and devices, have robust edge computing capabilities, provide real-time analytics and visualization, support machine learning model deployment for predictive maintenance and anomaly detection, have strong security features including end-to-end encryption and device authentication, and offer APIs for integration with other city management systems. It should also include features for managing and updating large fleets of IoT devices and support for creating digital twins of city infrastructure.',

  'Looking for a comprehensive game development engine that supports both 2D and 3D game creation, has a visual scripting system for non-programmers as well as support for multiple programming languages, includes advanced physics and AI systems, supports cross-platform development and deployment (including VR and AR platforms), has a robust asset management system, provides built-in analytics and player behavior tracking, supports multiplayer game development with scalable backend services, and has a marketplace for third-party assets and plugins. The engine should also have good documentation, an active community, and regular updates with cutting-edge graphics features.',

  'I need an end-to-end machine learning operations (MLOps) platform that supports the entire lifecycle of ML models from data preparation and feature engineering to model training, deployment, monitoring, and retraining. It should integrate with popular data science tools and notebooks, support distributed training on GPU clusters, provide version control for both data and models, have built-in experiment tracking and hyperparameter tuning capabilities, support A/B testing of models in production, offer explainable AI features, and provide drift detection and automated retraining triggers. The platform should be scalable to handle large datasets and complex models, and comply with data privacy regulations.',

  'Searching for a comprehensive design system and component library that supports multiple frontend frameworks (React, Vue, Angular), includes a wide range of accessible and customizable UI components, has built-in support for theming and dark mode, provides detailed documentation and live examples, includes design tokens for easy styling, supports icon customization and management, has utilities for responsive design and layout, includes animation and transition utilities, and provides tools for generating design system documentation. It should also have good TypeScript support, be performance-optimized, and include guidelines for usage and best practices.',

  'Need a robust digital asset management system that can handle a wide variety of file types including images, videos, 3D models, and documents. It should have AI-powered auto-tagging and categorization, support for managing brand assets and guidelines, version control and approval workflows, integration with popular design tools like Adobe Creative Suite and Figma, support for generating and managing different sizes and formats of assets, have strong search capabilities including visual search, provide usage analytics and rights management features, and offer APIs for integrating with other marketing and content management tools. The system should also support collaboration features and have a user-friendly interface for both technical and non-technical users.',

  'Looking for an advanced automated testing platform that supports end-to-end testing of web, mobile, and API-based applications. It should have a codeless test creation interface as well as support for scripting in multiple languages, include AI-powered test generation and self-healing capabilities, support parallel test execution and cross-browser testing, integrate with popular CI/CD tools, provide detailed test analytics and failure analysis, support testing of microservices architectures, include features for performance and security testing, and have robust test data management capabilities. The platform should also support visual testing for UI changes and have good support for testing single-page applications and progressive web apps.',
  "I'm developing a next-generation financial technology platform that needs to handle high-frequency trading, real-time risk assessment, and complex derivative pricing. I'm looking for a solution that combines ultra-low latency messaging systems, distributed ledger technology for transaction settlement, advanced machine learning algorithms for predictive analytics, and quantum computing integration for optimization problems. The platform should comply with financial regulations across multiple jurisdictions, support multi-factor authentication and advanced encryption, provide real-time auditing capabilities, and offer a customizable dashboard for risk management. Additionally, it should seamlessly integrate with existing banking systems, support multiple currencies including cryptocurrencies, and have robust disaster recovery and business continuity features.",

  "We're building a comprehensive smart agriculture ecosystem and need a platform that integrates IoT sensors, drone technology, satellite imagery, and weather data for precision farming. The solution should include machine learning models for crop yield prediction, pest and disease detection, and optimal resource allocation. It needs to support real-time monitoring and control of irrigation systems, automated farm equipment integration, and provide actionable insights through an intuitive mobile app for farmers. The platform should also incorporate blockchain for supply chain traceability, have features for carbon footprint tracking and sustainability reporting, support integration with agricultural marketplaces, and provide APIs for third-party agtech innovations. Additionally, it should handle offline operations in areas with limited connectivity and support multiple languages for global deployment.",

  'Seeking an advanced telehealth platform that supports virtual consultations, remote patient monitoring, and AI-assisted diagnostics. The platform should integrate with various medical IoT devices, support real-time video conferencing with AR capabilities for remote examinations, include natural language processing for automated note-taking and medical transcription, and have a robust EMR (Electronic Medical Record) system with interoperability features supporting HL7 and FHIR standards. It should incorporate machine learning for predictive health analytics, support integration with wearable devices for continuous health monitoring, include features for prescription management and e-pharmacy integration, and provide tools for managing chronic diseases. The platform must be HIPAA compliant, support multi-factor authentication, allow for secure sharing of medical imaging and lab results, and include billing and insurance claim management features. Additionally, it should have a patient portal with educational resources, appointment scheduling, and secure messaging capabilities.',

  'Looking for a comprehensive cybersecurity platform for a large multinational corporation. The solution should provide real-time threat detection and response capabilities, incorporate AI and machine learning for predictive threat analysis, support behavioral analytics to detect insider threats, and include advanced SIEM (Security Information and Event Management) features. It should offer robust endpoint protection across various operating systems and device types, provide network security with next-generation firewall capabilities, and include tools for continuous security posture assessment and compliance monitoring. The platform needs to support automated incident response and orchestration, have features for threat hunting and forensic analysis, and provide comprehensive reporting for regulatory compliance (GDPR, CCPA, etc.). Additionally, it should include a security awareness training module for employees, support integration with existing identity and access management systems, offer cloud security features including CASB (Cloud Access Security Broker) functionality, and have capabilities for securing IoT and OT (Operational Technology) environments.',

  'We need a cutting-edge augmented reality development platform for creating industrial applications. The platform should support markerless AR for large-scale environments, have robust SLAM (Simultaneous Localization and Mapping) capabilities, and integrate with CAD software for importing 3D models. It should offer cross-platform development for various AR headsets (HoloLens, Magic Leap, mobile devices) and include features for collaborative AR experiences in multi-user environments. The platform needs to support real-time data visualization from IoT sensors, have AI-powered object recognition and tracking capabilities, and provide tools for creating step-by-step AR workflows for maintenance and training scenarios. It should include a visual programming interface for non-developers as well as SDKs for multiple programming languages. The platform must have strong security features for protecting sensitive industrial data, support offline functionality for use in areas with limited connectivity, and provide analytics on AR application usage and performance. Additionally, it should offer cloud-based services for heavy computational tasks, have features for remote expert assistance, and support integration with existing enterprise systems like ERP and MES.',

  'Searching for an advanced natural language processing platform for building sophisticated conversational AI and language understanding applications. The platform should support training of custom language models, offer pre-trained models for various domains and languages, and provide tools for active learning and continuous model improvement. It needs to include features for intent recognition, named entity extraction, sentiment analysis, and multi-turn dialogue management. The platform should support multi-modal inputs (text, voice, images) and have capabilities for speech recognition and synthesis across multiple languages and accents. It should offer tools for building and managing knowledge graphs, support contextual understanding and memory in conversations, and provide features for personality customization in chatbots. The platform needs to have robust APIs and SDKs for easy integration into various applications, support deployment on-premises or in the cloud, and offer scalable infrastructure for handling high volumes of requests. Additionally, it should include analytics and visualization tools for conversation insights, support A/B testing of different conversational flows, have features for handling edge cases and fallback scenarios, and provide tools for compliance with conversational AI regulations and ethical guidelines.',

  'Need a comprehensive digital twin platform for modeling and simulating complex industrial systems. The platform should support integration with various data sources including IoT sensors, historical databases, and real-time data streams. It needs to offer high-fidelity 3D visualization capabilities, support physics-based simulations for predicting system behavior, and include features for real-time monitoring and anomaly detection. The platform should have capabilities for predictive maintenance, optimization of operational parameters, and what-if scenario analysis. It needs to support the creation of hierarchical and interconnected digital twins (from component level to system-of-systems level) and provide tools for managing the entire lifecycle of digital twins. The platform should offer collaborative features for multiple users to work on the same digital twin model, support version control and change management, and provide APIs for integration with other enterprise systems like ERP and MES. It should include machine learning capabilities for improving model accuracy over time, support edge computing for distributed processing, and offer features for augmented reality visualization of digital twin data. Additionally, the platform needs to have robust security features, support role-based access control, provide comprehensive audit trails, and offer scalable cloud-based deployment options.',

  'Looking for an advanced robotic process automation (RPA) platform with cognitive capabilities for automating complex business processes. The platform should support both attended and unattended automation, offer a low-code/no-code interface for business users as well as advanced scripting capabilities for developers. It needs to include AI-powered document understanding for processing unstructured data, have natural language processing capabilities for interpreting and generating human language, and support computer vision for interacting with various application interfaces and handling captchas. The platform should offer orchestration capabilities for managing complex workflows across multiple systems and departments, provide tools for process mining and task discovery, and include features for measuring and optimizing automation ROI. It needs to have robust governance and control mechanisms, support version control and release management for bots, and offer detailed analytics on bot performance and business impact. The platform should seamlessly integrate with enterprise systems (SAP, Salesforce, etc.), support automation in virtual and Citrix environments, and offer cloud, on-premises, and hybrid deployment options. Additionally, it should include features for attended automation like guided assistance and human-in-the-loop workflows, support mobile interfaces for bot management and monitoring, and provide tools for ensuring compliance with industry regulations and internal policies.',
];

export const mainLoadingTips = [
    // Existing developer-focused tips
    'AweSearch uses AI to find the perfect tools for your needs.',
    'Our database includes thousands of tools and resources for entrepreneurs and developers.',
    'AweSearch can help you discover both free and premium solutions.',
    'Use specific keywords to get more targeted results.',
    'AweSearch is constantly updated with the latest tools and resources.',
    'Looking for a specific feature? Include it in your search query!',
    'AweSearch can help you find alternatives to popular tools.',
    "Don't forget to check the 'View Details' for in-depth information about each tool.",
]

export const additionalLoadingTips = [
    // New entrepreneur-focused tips
    'Discover no-code platforms to build your MVP without coding skills.',
    'Find marketing automation tools to streamline your promotional efforts.',
    'Explore email marketing services to engage with your audience effectively.',
    'Uncover SEO tools to improve your website\'s visibility in search results.',
    'Discover design tools for creating professional logos and branding materials.',
    'Find project management tools to keep your solo venture organized.',
    'Explore e-commerce platforms to set up your online store quickly.',
    'Uncover customer relationship management (CRM) tools for better client interactions.',
    'Find social media management tools to boost your online presence.',
    'Discover analytics tools to track and improve your website\'s performance.',
    'Explore stock photo and video libraries for high-quality visual content.',
    'Find landing page builders to create high-converting pages for your product.',
    'Uncover survey and feedback tools to gather valuable user insights.',
    'Discover accounting and invoicing tools to manage your finances efficiently.',
    'Find legal document generators to help with contracts and agreements.',
    'Explore video editing tools for creating engaging product demos and content.',
    'Uncover tools for creating and managing online courses or webinars.',
    'Find A/B testing tools to optimize your website and marketing campaigns.',
    'Discover virtual assistant services to help with administrative tasks.',
    'Explore productivity and time management tools to maximize your efficiency.',
    'Find tools for creating interactive prototypes to test your product ideas.',
    'Uncover crowdfunding platforms to finance your entrepreneurial venture.',
    'Discover tools for creating eye-catching infographics and presentations.',
    'Find resources for learning essential business and marketing skills.',
    'Explore tools for conducting market research and competitor analysis.',
    'Uncover website builders with built-in SEO and marketing features.',
    'Find tools for creating and managing affiliate marketing programs.',
    'Discover AI-powered tools to automate various aspects of your business.',
  ];